### ISSUE TITLE
Add “retired“ box

### ISSUE THREAD

**Issue by yatil** [w3c/wai-shared-experiences#2]
See: w3c/wai-website-design#125

**Comment by yatil** [comment]
@slhenry You might want to change the text for the archive box here: https://github.com/w3c/wai-shared-experiences/commit/2affb231242d502a7412aab5f121da9135fbacb4

**Comment by shawna-slh** [comment]
Thanks for getting this started.

Here's what we want in the archive box: 
```
<p><strong>If you want current information on <em>mobile accessibility</em> &mdash; that is, people with disabilities using content on mobile devices, see <a  href="https://www.w3.org/WAI/mobile/">https://www.w3.org/WAI/mobile/</a></strong></p>
<p>This page is archived. We do not plan to update it. It was developed in 2008. Much of the information is still relevant today. It is useful for understanding that:</p>
<ul>
  <li>Many of the issues around designing for mobile devices are addressed by designing for people with disabilities.</li>
  <li>When you address accessibility, you improve the mobile experience. This can help in presenting your business case for accessibility.</li>
</ul>
```
(tweaked from https://www.w3.org/WAI/EO/wiki/Mobile_Resources#Top_of_page )

Note that it should not start with "Archived:".

I tried to do it myself, but it broke. I guess you need to set it up to handle html, like the footer.

**Comment by shawna-slh** [comment]
I think this can wait until after beta announce if needed

**Comment by yatil** [comment]
We did agree to have archived before the text in the box <del>last week</del> <ins>two weeks ago</ins> and one sentence after it. I’ll remodel it. I think it needs to be in place for the beta.

**Comment by yatil** [comment]
Instead of the rather simple

```yaml
archive: your message text
```

we now specify the `doc-note-type` first (`archived` or `draft`) and then add the `doc-note-message: >` with the message in HTML format (every new line with a two space indent):

```yaml
doc-note-type: archived
doc-note-message: >
  <p><strong>If you want current information on <em>mobile accessibility</em> &mdash; that is, people with disabilities using content on mobile devices, see <a  href="https://www.w3.org/WAI/mobile/">https://www.w3.org/WAI/mobile/</a></strong></p>
  <p>This page is archived. We do not plan to update it. It was developed in 2008. Much of the information is still relevant today. It is useful for understanding that:</p>
  <ul>
    <li>Many of the issues around designing for mobile devices are addressed by designing for people with disabilities.</li>
    <li>When you address accessibility, you improve the mobile experience. This can help in presenting your business case for accessibility.</li>
  </ul>
```

I’ve done that here.
