### ISSUE TITLE
[low] wcag 1.0 bullets gray

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-shared-experiences#4]
see https://www.w3.org/WAI/mobile/experiences

**Comment by yatil** [comment]
I deliberately didn’t add this for contrast reasons. Feel free to pick a contrasting gray from the list of colors we use and propose a class name. (On the old site, the color just barely has a 4.5:1 contrast ratio, we want 7:1 for the new site. And maybe also a 4.5:1 contrast to the default body text to get to WCAG 2.1 conformance.)
