### ISSUE TITLE
[high] internal links under "Contents"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-shared-experiences#5]
seem no worky?

**Comment by yatil** [comment]
Yes, the content is not checked for rendering as noted in #1 (4th bullet). The site is not yet using the proper contents code. This is done when I link it to the main repository. I hope to get to it today. This is stuff that needs to be ready for the beta. The beta site should work like the proper site. That’s the goal. If we don’t fix links before it, we cannot call it beta.
